// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	utils "github.com/ifaniqbal/go-base-project/internal/utils"
	mock "github.com/stretchr/testify/mock"
)

// GroupHandler is an autogenerated mock type for the GroupHandler type
type GroupHandler struct {
	mock.Mock
}

type GroupHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *GroupHandler) EXPECT() *GroupHandler_Expecter {
	return &GroupHandler_Expecter{mock: &_m.Mock}
}

// Group provides a mock function with given fields: relativePath, handles
func (_m *GroupHandler) Group(relativePath string, handles ...utils.HandlerFunc) utils.RouteHandler {
	_va := make([]interface{}, len(handles))
	for _i := range handles {
		_va[_i] = handles[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, relativePath)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 utils.RouteHandler
	if rf, ok := ret.Get(0).(func(string, ...utils.HandlerFunc) utils.RouteHandler); ok {
		r0 = rf(relativePath, handles...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(utils.RouteHandler)
		}
	}

	return r0
}

// GroupHandler_Group_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Group'
type GroupHandler_Group_Call struct {
	*mock.Call
}

// Group is a helper method to define mock.On call
//   - relativePath string
//   - handles ...utils.HandlerFunc
func (_e *GroupHandler_Expecter) Group(relativePath interface{}, handles ...interface{}) *GroupHandler_Group_Call {
	return &GroupHandler_Group_Call{Call: _e.mock.On("Group",
		append([]interface{}{relativePath}, handles...)...)}
}

func (_c *GroupHandler_Group_Call) Run(run func(relativePath string, handles ...utils.HandlerFunc)) *GroupHandler_Group_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]utils.HandlerFunc, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(utils.HandlerFunc)
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *GroupHandler_Group_Call) Return(_a0 utils.RouteHandler) *GroupHandler_Group_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GroupHandler_Group_Call) RunAndReturn(run func(string, ...utils.HandlerFunc) utils.RouteHandler) *GroupHandler_Group_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewGroupHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewGroupHandler creates a new instance of GroupHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGroupHandler(t mockConstructorTestingTNewGroupHandler) *GroupHandler {
	mock := &GroupHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
