// The tests were generated by ChatGPT, an AI language model by OpenAI.

package environment

import (
	"os"
	"testing"
)

func TestOsEnvironment_Get(t *testing.T) {
	// Arrange
	err := os.Setenv("test_key", "test_value")
	if err != nil {
		return
	}
	e := Default()

	// Act
	value := e.Get("test_key")

	// Assert
	if value != "test_value" {
		t.Errorf("Expected 'test_value' but got '%s'", value)
	}
}

func TestOsEnvironment_GetUint(t *testing.T) {
	// Arrange
	err := os.Setenv("test_key", "100")
	if err != nil {
		return
	}
	e := Default()

	// Act
	value := e.GetUint("test_key", 200)

	// Assert
	expected := uint(100)
	if value != expected {
		t.Errorf("Expected '%d' but got '%d'", expected, value)
	}
}

func TestOsEnvironment_GetUint_withError(t *testing.T) {
	// Arrange
	err := os.Setenv("test_key", "invalid_value")
	if err != nil {
		return
	}
	e := Default()

	// Act
	value := e.GetUint("test_key", 200)

	// Assert
	expected := uint(200)
	if value != expected {
		t.Errorf("Expected '%d' but got '%d'", expected, value)
	}
}
