// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	io "io"

	exporter "github.com/ifaniqbal/go-base-project/pkg/exporter"

	mock "github.com/stretchr/testify/mock"
)

// CSVWriterCreator is an autogenerated mock type for the CSVWriterCreator type
type CSVWriterCreator struct {
	mock.Mock
}

type CSVWriterCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *CSVWriterCreator) EXPECT() *CSVWriterCreator_Expecter {
	return &CSVWriterCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: writer
func (_m *CSVWriterCreator) Create(writer io.Writer) exporter.CSVWriteFlusher {
	ret := _m.Called(writer)

	var r0 exporter.CSVWriteFlusher
	if rf, ok := ret.Get(0).(func(io.Writer) exporter.CSVWriteFlusher); ok {
		r0 = rf(writer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(exporter.CSVWriteFlusher)
		}
	}

	return r0
}

// CSVWriterCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type CSVWriterCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - writer io.Writer
func (_e *CSVWriterCreator_Expecter) Create(writer interface{}) *CSVWriterCreator_Create_Call {
	return &CSVWriterCreator_Create_Call{Call: _e.mock.On("Create", writer)}
}

func (_c *CSVWriterCreator_Create_Call) Run(run func(writer io.Writer)) *CSVWriterCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Writer))
	})
	return _c
}

func (_c *CSVWriterCreator_Create_Call) Return(_a0 exporter.CSVWriteFlusher) *CSVWriterCreator_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CSVWriterCreator_Create_Call) RunAndReturn(run func(io.Writer) exporter.CSVWriteFlusher) *CSVWriterCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewCSVWriterCreator interface {
	mock.TestingT
	Cleanup(func())
}

// NewCSVWriterCreator creates a new instance of CSVWriterCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCSVWriterCreator(t mockConstructorTestingTNewCSVWriterCreator) *CSVWriterCreator {
	mock := &CSVWriterCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
