// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	exporter "github.com/ifaniqbal/go-base-project/pkg/exporter"
	mock "github.com/stretchr/testify/mock"
)

// ExcelWriterCreator is an autogenerated mock type for the ExcelWriterCreator type
type ExcelWriterCreator struct {
	mock.Mock
}

type ExcelWriterCreator_Expecter struct {
	mock *mock.Mock
}

func (_m *ExcelWriterCreator) EXPECT() *ExcelWriterCreator_Expecter {
	return &ExcelWriterCreator_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields:
func (_m *ExcelWriterCreator) Create() exporter.ExcelWriter {
	ret := _m.Called()

	var r0 exporter.ExcelWriter
	if rf, ok := ret.Get(0).(func() exporter.ExcelWriter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(exporter.ExcelWriter)
		}
	}

	return r0
}

// ExcelWriterCreator_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ExcelWriterCreator_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
func (_e *ExcelWriterCreator_Expecter) Create() *ExcelWriterCreator_Create_Call {
	return &ExcelWriterCreator_Create_Call{Call: _e.mock.On("Create")}
}

func (_c *ExcelWriterCreator_Create_Call) Run(run func()) *ExcelWriterCreator_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ExcelWriterCreator_Create_Call) Return(_a0 exporter.ExcelWriter) *ExcelWriterCreator_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ExcelWriterCreator_Create_Call) RunAndReturn(run func() exporter.ExcelWriter) *ExcelWriterCreator_Create_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewExcelWriterCreator interface {
	mock.TestingT
	Cleanup(func())
}

// NewExcelWriterCreator creates a new instance of ExcelWriterCreator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewExcelWriterCreator(t mockConstructorTestingTNewExcelWriterCreator) *ExcelWriterCreator {
	mock := &ExcelWriterCreator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
